version: '3.1'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile-backend
        ports:
            - "80:80"
        restart: always
        image: backend
        env_file:
          - backend/private.env