version: '3.1'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile-backend
        depends_on:
          - db
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./backend:/src/
        image: backend
        env_file:
           - backend/private.env
        links:
          - db
        networks:
          db:
    db:
        build:
            context: ./backend
            dockerfile: Dockerfile-db
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgrespassword
            - POSTGRES_USER=soundtrackdb
        ports:
            - "5432:5432"
        networks:
          db:
networks:
  db: