version: '3.1'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile-backend
        depends_on:
          - db
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./backend:/src/
        env_file:
           - backend/private.env
        links:
          - db
        networks:
          db:
        environment:
          - POSTGRES_URL=db
          - POSTGRES_PASSWORD=postgrespassword
          - POSTGRES_USER=soundtrackdb
          - POSTGRES_DB=soundtrackdb
    db:
        build:
            context: ./backend
            dockerfile: Dockerfile-db
        volumes:
            - ./postgres-data/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgrespassword
            - POSTGRES_USER=soundtrackdb
        ports:
            - "5432:5432"
        networks:
          db:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile-frontend
        ports:
            - "3000:3000"
            - "35729:35729"
        restart: always
        volumes:
            - ./frontend:/app/
            - /app/node_modules
        depends_on:
          - backend
networks:
  db: