version: '3.1'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile-backend
        ports:
            - "80:80"
        restart: always
        image: backend
        env_file:
           - backend/db.env
           - backend/private.env
        environment:
          - POSTGRES_URL=soundtrackdb.c0qwjarqhqxf.us-east-2.rds.amazonaws.com