version: '3.1'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./:/src/
        image: backend
        env_file:
          - private.env